[package]
name = "pty2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.144"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["full"] }
